---
# Minimal playbook for post-chroot: user creation and XFCE4 (ASTER/YUGEN only).
# Used by prep.sh after base system install. Run from inside chroot with:
#   ansible-playbook chroot.yml -i inventory.yml --ask-vault-pass
#
# Requires: vault (vars), roles ansible-role-user, ansible-role-xfce4

- name: Configure users and XFCE4 in chroot
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - vault

  pre_tasks:
    - name: Read hostname from /etc/hostname
      ansible.builtin.slurp:
        src: /etc/hostname
      register: hostname_file

    - name: Set hostname fact
      ansible.builtin.set_fact:
        current_hostname: "{{ (hostname_file.content | b64decode).strip() | upper }}"
        current_hostname_raw: "{{ (hostname_file.content | b64decode).strip() }}"

    - name: Verify hostname is ASTER or YUGEN
      ansible.builtin.assert:
        that:
          - current_hostname in ['ASTER', 'YUGEN']
        fail_msg: "chroot.yml only runs on ASTER or YUGEN. Current hostname: {{ current_hostname }}"

    - name: Set hostname variables for roles
      ansible.builtin.set_fact:
        cached_hostname: "{{ current_hostname }}"
        cached_hostname_raw: "{{ current_hostname_raw }}"
        hostname: "{{ current_hostname }}"
        cacheable: true

  roles:
    - role: ansible-role-user
    - role: ansible-role-xfce4
