---
# Workstation Playbook
# Runs on ASTER and YUGEN hosts only
#
# Usage:
#   ansible-playbook workstation.yml --ask-vault-pass
#   ansible-playbook workstation.yml --vault-password-file=~/.vault_pass
#
# Execution Flow:
#   1. user      - Create users, SSH keys, shell configs
#   2. os        - Locale, network, NTP, services
#   3. pipewire  - Audio stack
#   4. gpu       - Graphics drivers
#   5. xfce4     - Desktop environment, LightDM, bluetooth
#   6. gaming    - Steam, Lutris, gamemode
#   7. onedrive  - OneDrive client installation and setup
#   8. bootstrap - OneDrive sync (interactive), symlinks, XFCE config
#
# NOTE: The bootstrap role will pause for OneDrive authentication.
# Follow the on-screen instructions to authenticate with Microsoft.

- name: Configure workstation
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - vault

  pre_tasks:
    - name: Read hostname from /etc/hostname
      ansible.builtin.slurp:
        src: /etc/hostname
      register: hostname_file

    - name: Set hostname fact
      ansible.builtin.set_fact:
        current_hostname: "{{ (hostname_file.content | b64decode).strip() | upper }}"

    - name: Display detected hostname
      ansible.builtin.debug:
        msg: "Detected hostname: {{ current_hostname }}"

    - name: Verify hostname is ASTER or YUGEN
      ansible.builtin.assert:
        that:
          - current_hostname in ['ASTER', 'YUGEN']
        fail_msg: "This playbook only runs on ASTER or YUGEN. Current hostname: {{ current_hostname }}"
        success_msg: "Hostname verified: {{ current_hostname }}"

    - name: Set hostname variables for roles
      ansible.builtin.set_fact:
        cached_hostname: "{{ current_hostname }}"
        hostname: "{{ current_hostname }}"
        cacheable: true

    - name: Set host-specific bootstrap variables for ASTER
      ansible.builtin.set_fact:
        bootstrap_xfce_monitors:
          - "eDP-1"
          - "DP-1-1"
      when: current_hostname == 'ASTER'

    - name: Set host-specific bootstrap variables for YUGEN
      ansible.builtin.set_fact:
        bootstrap_xfce_monitors:
          - "DP-1"
          - "DP-2"
          - "DP-3"
      when: current_hostname == 'YUGEN'

  roles:
    - role: ansible-role-user
      tags: [user]

    - role: ansible-role-os
      tags: [os]

    - role: ansible-role-pipewire
      tags: [pipewire]

    - role: ansible-role-gpu
      tags: [gpu]

    - role: ansible-role-xfce4
      tags: [xfce4]

    - role: ansible-role-gaming
      tags: [gaming]

    - role: ansible-role-onedrive
      tags: [onedrive]

    - role: ansible-role-bootstrap
      tags: [bootstrap]
